version: "2"
services:
  app:
    image: flaskapp
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
